<?php
/**
 * Schedule/Calendar
 */

global $pfob_project;

PFOB_Template::header( $pfob_project->name . ' - Schedule' );

$current_month = isset( $_GET['month'] ) ? intval( $_GET['month'] ) : date( 'n' );
$current_year = isset( $_GET['year'] ) ? intval( $_GET['year'] ) : date( 'Y' );

$events = PFOB_Event::get_project_events(
    $pfob_project->id,
    "$current_year-$current_month-01",
    date( 'Y-m-t', strtotime( "$current_year-$current_month-01" ) )
);
?>

<div class="pfob-container">
    <?php PFOB_Template::navigation(); ?>

    <main class="pfob-main pfob-schedule">

        <div class="pfob-page-header">
            <h1>Schedule</h1>
            <div class="pfob-actions">
                <button class="pfob-btn pfob-btn-secondary" id="export-ical-btn">
                    Export iCal
                </button>
                <button class="pfob-btn pfob-btn-primary" id="new-event-btn">
                    New Event
                </button>
            </div>
        </div>

        <div class="pfob-calendar-controls">
            <button id="prev-month">&larr;</button>
            <h2 id="current-month-year"><?php echo date( 'F Y', strtotime( "$current_year-$current_month-01" ) ); ?></h2>
            <button id="next-month">&rarr;</button>
        </div>

        <div class="pfob-calendar" id="calendar-grid">
            <!-- Calendar will be generated by JavaScript -->
        </div>

        <div class="pfob-upcoming-events">
            <h3>Upcoming Events</h3>
            <div id="upcoming-events-list">
                <?php
                $upcoming = PFOB_Event::get_upcoming_events( $pfob_project->id, 10 );
                if ( empty( $upcoming ) ) :
                ?>
                    <p>No upcoming events</p>
                <?php else : ?>
                    <?php foreach ( $upcoming as $event ) : ?>
                        <div class="pfob-event-item">
                            <div class="pfob-event-date"><?php echo date( 'M j', strtotime( $event->start_datetime ) ); ?></div>
                            <div class="pfob-event-details">
                                <strong><?php echo esc_html( $event->title ); ?></strong>
                                <?php if ( $event->location ) : ?>
                                    <span>📍 <?php echo esc_html( $event->location ); ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>

    </main>
</div>

<script>
const pfobData = {
    restUrl: '<?php echo rest_url( 'projectfob/v1' ); ?>',
    nonce: '<?php echo wp_create_nonce( 'wp_rest' ); ?>',
    projectId: <?php echo $pfob_project->id; ?>,
    currentMonth: <?php echo $current_month; ?>,
    currentYear: <?php echo $current_year; ?>,
    events: <?php echo json_encode( $events ); ?>
};

function renderCalendar() {
    const firstDay = new Date(pfobData.currentYear, pfobData.currentMonth - 1, 1);
    const lastDay = new Date(pfobData.currentYear, pfobData.currentMonth, 0);
    const daysInMonth = lastDay.getDate();
    const startDay = firstDay.getDay();

    let html = '<div class="pfob-calendar-header">';
    ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].forEach(day => {
        html += `<div class="pfob-calendar-day-name">${day}</div>`;
    });
    html += '</div><div class="pfob-calendar-days">';

    for (let i = 0; i < startDay; i++) {
        html += '<div class="pfob-calendar-cell pfob-empty"></div>';
    }

    for (let day = 1; day <= daysInMonth; day++) {
        const dateStr = `${pfobData.currentYear}-${String(pfobData.currentMonth).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const dayEvents = pfobData.events.filter(e => e.start_datetime.startsWith(dateStr));

        html += `<div class="pfob-calendar-cell" data-date="${dateStr}">
            <div class="pfob-day-number">${day}</div>
            <div class="pfob-day-events">`;

        dayEvents.forEach(event => {
            html += `<div class="pfob-event-dot" title="${event.title}"></div>`;
        });

        html += '</div></div>';
    }

    html += '</div>';
    document.getElementById('calendar-grid').innerHTML = html;

    document.querySelectorAll('.pfob-calendar-cell[data-date]').forEach(cell => {
        cell.addEventListener('click', () => {
            const date = cell.dataset.date;
            showCreateEventModal(date);
        });
    });
}

document.getElementById('prev-month').addEventListener('click', () => {
    pfobData.currentMonth--;
    if (pfobData.currentMonth < 1) {
        pfobData.currentMonth = 12;
        pfobData.currentYear--;
    }
    window.location.href = `?month=${pfobData.currentMonth}&year=${pfobData.currentYear}`;
});

document.getElementById('next-month').addEventListener('click', () => {
    pfobData.currentMonth++;
    if (pfobData.currentMonth > 12) {
        pfobData.currentMonth = 1;
        pfobData.currentYear++;
    }
    window.location.href = `?month=${pfobData.currentMonth}&year=${pfobData.currentYear}`;
});

document.getElementById('new-event-btn').addEventListener('click', () => {
    showCreateEventModal();
});

document.getElementById('export-ical-btn').addEventListener('click', () => {
    window.location.href = `${pfobData.restUrl}/projects/${pfobData.projectId}/events/ical`;
});

function showCreateEventModal(date = null) {
    const modal = document.createElement('div');
    modal.className = 'pfob-modal';
    modal.innerHTML = `
        <div class="pfob-modal-content">
            <div class="pfob-modal-header">
                <h2>New Event</h2>
                <button class="pfob-modal-close">&times;</button>
            </div>
            <div class="pfob-modal-body">
                <form id="create-event-form">
                    <div class="pfob-form-group">
                        <label>Event Title *</label>
                        <input type="text" name="title" required>
                    </div>
                    <div class="pfob-form-group">
                        <label>Description</label>
                        <textarea name="description" rows="3"></textarea>
                    </div>
                    <div class="pfob-form-group">
                        <label>Start Date/Time *</label>
                        <input type="datetime-local" name="start_datetime" required value="${date ? date + 'T09:00' : ''}">
                    </div>
                    <div class="pfob-form-group">
                        <label>End Date/Time *</label>
                        <input type="datetime-local" name="end_datetime" required value="${date ? date + 'T10:00' : ''}">
                    </div>
                    <div class="pfob-form-group">
                        <label>Location</label>
                        <input type="text" name="location">
                    </div>
                    <div class="pfob-form-actions">
                        <button type="submit" class="pfob-btn pfob-btn-primary">Create Event</button>
                        <button type="button" class="pfob-btn pfob-btn-secondary pfob-modal-close">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    `;

    document.body.appendChild(modal);

    modal.querySelectorAll('.pfob-modal-close').forEach(btn => {
        btn.addEventListener('click', () => modal.remove());
    });

    document.getElementById('create-event-form').addEventListener('submit', async (e) => {
        e.preventDefault();
        const formData = new FormData(e.target);
        const data = {
            title: formData.get('title'),
            description: formData.get('description'),
            location: formData.get('location'),
            start_datetime: formData.get('start_datetime'),
            end_datetime: formData.get('end_datetime')
        };

        try {
            const response = await fetch(`${pfobData.restUrl}/projects/${pfobData.projectId}/events`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-WP-Nonce': pfobData.nonce
                },
                body: JSON.stringify(data)
            });

            if (response.ok) {
                modal.remove();
                window.location.reload();
            }
        } catch (error) {
            console.error('Failed to create event:', error);
        }
    });
}

renderCalendar();
</script>

<style>
.pfob-calendar-controls {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin: 30px 0;
    padding: 0 20px;
}

.pfob-calendar-controls button {
    background: #2d9061;
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
    transition: background 0.2s;
}

.pfob-calendar-controls button:hover {
    background: #247a50;
}

.pfob-calendar-controls h2 {
    margin: 0;
    color: #333;
    font-size: 24px;
}

.pfob-calendar {
    background: white;
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 30px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

.pfob-calendar-header {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    margin-bottom: 10px;
    background: #e0e0e0;
    border: 1px solid #e0e0e0;
}

.pfob-calendar-day-name {
    text-align: center;
    font-weight: 600;
    padding: 12px;
    background: #f7f6f3;
    color: #666;
    font-size: 14px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}

.pfob-calendar-days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    background: #e0e0e0;
    border: 1px solid #e0e0e0;
}

.pfob-calendar-cell {
    background: white;
    min-height: 100px;
    padding: 8px;
    cursor: pointer;
    position: relative;
    transition: background 0.2s;
}

.pfob-calendar-cell.pfob-empty {
    background: #f9f9f9;
    cursor: default;
}

.pfob-calendar-cell:hover:not(.pfob-empty) {
    background: #f0f9f4;
}

.pfob-day-number {
    font-weight: 600;
    margin-bottom: 5px;
    color: #333;
    font-size: 14px;
}

.pfob-day-events {
    display: flex;
    flex-wrap: wrap;
    gap: 3px;
    margin-top: 5px;
}

.pfob-event-dot {
    width: 8px;
    height: 8px;
    background: #2d9061;
    border-radius: 50%;
    cursor: pointer;
}

.pfob-event-dot:hover {
    background: #247a50;
    transform: scale(1.2);
}

.pfob-upcoming-events {
    background: white;
    border-radius: 8px;
    padding: 25px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

.pfob-upcoming-events h3 {
    margin-top: 0;
    margin-bottom: 20px;
    color: #333;
    font-size: 20px;
}

.pfob-event-item {
    display: flex;
    gap: 15px;
    padding: 15px;
    border-bottom: 1px solid #eee;
    transition: background 0.2s;
}

.pfob-event-item:hover {
    background: #f9f9f9;
}

.pfob-event-item:last-child {
    border-bottom: none;
}

.pfob-event-date {
    flex-shrink: 0;
    width: 60px;
    text-align: center;
    font-weight: 600;
    color: #2d9061;
    font-size: 16px;
}

.pfob-event-details {
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    gap: 5px;
}

.pfob-event-details strong {
    color: #333;
    font-size: 16px;
}

.pfob-event-details span {
    font-size: 14px;
    color: #666;
}

/* Modal styles */
.pfob-modal {
    display: flex;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
    z-index: 10000;
    align-items: center;
    justify-content: center;
}

.pfob-modal-content {
    background: white;
    border-radius: 8px;
    max-width: 500px;
    width: 90%;
    max-height: 90vh;
    overflow-y: auto;
    box-shadow: 0 4px 20px rgba(0,0,0,0.3);
}

.pfob-modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 20px;
    border-bottom: 1px solid #eee;
}

.pfob-modal-header h2 {
    margin: 0;
    font-size: 20px;
    color: #333;
}

.pfob-modal-close {
    background: none;
    border: none;
    font-size: 28px;
    cursor: pointer;
    color: #999;
    line-height: 1;
    padding: 0;
    width: 30px;
    height: 30px;
}

.pfob-modal-close:hover {
    color: #333;
}

.pfob-modal-body {
    padding: 20px;
}

.pfob-form-group {
    margin-bottom: 20px;
}

.pfob-form-group label {
    display: block;
    margin-bottom: 8px;
    font-weight: 600;
    color: #333;
}

.pfob-form-group input,
.pfob-form-group textarea {
    width: 100%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 14px;
    font-family: inherit;
}

.pfob-form-group input:focus,
.pfob-form-group textarea:focus {
    outline: none;
    border-color: #2d9061;
}

.pfob-form-actions {
    display: flex;
    gap: 10px;
    justify-content: flex-end;
    margin-top: 20px;
}

/* Today's date highlight */
.pfob-calendar-cell.pfob-today .pfob-day-number {
    background: #2d9061;
    color: white;
    width: 28px;
    height: 28px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
}

/* Responsive */
@media (max-width: 768px) {
    .pfob-calendar-cell {
        min-height: 80px;
        padding: 5px;
    }

    .pfob-day-number {
        font-size: 12px;
    }

    .pfob-event-dot {
        width: 6px;
        height: 6px;
    }

    .pfob-calendar-controls h2 {
        font-size: 18px;
    }
}
</style>

<script src="<?php echo PFOB_PLUGIN_URL; ?>assets/js/frontend.js?ver=<?php echo PFOB_VERSION; ?>"></script>

</body>
</html>
