<?php
/**
 * Schedule/Calendar
 */

global $bcwp_project;

BCWP_Template::header( $bcwp_project->name . ' - Schedule' );

$current_month = isset( $_GET['month'] ) ? intval( $_GET['month'] ) : date( 'n' );
$current_year = isset( $_GET['year'] ) ? intval( $_GET['year'] ) : date( 'Y' );

$events = BCWP_Event::get_project_events(
    $bcwp_project->id,
    "$current_year-$current_month-01",
    date( 'Y-m-t', strtotime( "$current_year-$current_month-01" ) )
);
?>

<div class="bcwp-container">
    <?php BCWP_Template::navigation(); ?>

    <main class="bcwp-main bcwp-schedule">

        <div class="bcwp-page-header">
            <h1>Schedule</h1>
            <div class="bcwp-actions">
                <button class="bcwp-btn bcwp-btn-secondary" id="export-ical-btn">
                    Export iCal
                </button>
                <button class="bcwp-btn bcwp-btn-primary" id="new-event-btn">
                    New Event
                </button>
            </div>
        </div>

        <div class="bcwp-calendar-controls">
            <button id="prev-month">&larr;</button>
            <h2 id="current-month-year"><?php echo date( 'F Y', strtotime( "$current_year-$current_month-01" ) ); ?></h2>
            <button id="next-month">&rarr;</button>
        </div>

        <div class="bcwp-calendar" id="calendar-grid">
            <!-- Calendar will be generated by JavaScript -->
        </div>

        <div class="bcwp-upcoming-events">
            <h3>Upcoming Events</h3>
            <div id="upcoming-events-list">
                <?php
                $upcoming = BCWP_Event::get_upcoming_events( $bcwp_project->id, 10 );
                if ( empty( $upcoming ) ) :
                ?>
                    <p>No upcoming events</p>
                <?php else : ?>
                    <?php foreach ( $upcoming as $event ) : ?>
                        <div class="bcwp-event-item">
                            <div class="bcwp-event-date"><?php echo date( 'M j', strtotime( $event->start_datetime ) ); ?></div>
                            <div class="bcwp-event-details">
                                <strong><?php echo esc_html( $event->title ); ?></strong>
                                <?php if ( $event->location ) : ?>
                                    <span>📍 <?php echo esc_html( $event->location ); ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>

    </main>
</div>

<script>
const bcwpData = {
    restUrl: '<?php echo rest_url( 'bcwp/v1' ); ?>',
    nonce: '<?php echo wp_create_nonce( 'wp_rest' ); ?>',
    projectId: <?php echo $bcwp_project->id; ?>,
    currentMonth: <?php echo $current_month; ?>,
    currentYear: <?php echo $current_year; ?>,
    events: <?php echo json_encode( $events ); ?>
};

function renderCalendar() {
    const firstDay = new Date(bcwpData.currentYear, bcwpData.currentMonth - 1, 1);
    const lastDay = new Date(bcwpData.currentYear, bcwpData.currentMonth, 0);
    const daysInMonth = lastDay.getDate();
    const startDay = firstDay.getDay();

    let html = '<div class="bcwp-calendar-header">';
    ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].forEach(day => {
        html += `<div class="bcwp-calendar-day-name">${day}</div>`;
    });
    html += '</div><div class="bcwp-calendar-days">';

    for (let i = 0; i < startDay; i++) {
        html += '<div class="bcwp-calendar-cell bcwp-empty"></div>';
    }

    for (let day = 1; day <= daysInMonth; day++) {
        const dateStr = `${bcwpData.currentYear}-${String(bcwpData.currentMonth).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const dayEvents = bcwpData.events.filter(e => e.start_datetime.startsWith(dateStr));

        html += `<div class="bcwp-calendar-cell" data-date="${dateStr}">
            <div class="bcwp-day-number">${day}</div>
            <div class="bcwp-day-events">`;

        dayEvents.forEach(event => {
            html += `<div class="bcwp-event-dot" title="${event.title}"></div>`;
        });

        html += '</div></div>';
    }

    html += '</div>';
    document.getElementById('calendar-grid').innerHTML = html;

    document.querySelectorAll('.bcwp-calendar-cell[data-date]').forEach(cell => {
        cell.addEventListener('click', () => {
            const date = cell.dataset.date;
            showCreateEventModal(date);
        });
    });
}

document.getElementById('prev-month').addEventListener('click', () => {
    bcwpData.currentMonth--;
    if (bcwpData.currentMonth < 1) {
        bcwpData.currentMonth = 12;
        bcwpData.currentYear--;
    }
    window.location.href = `?month=${bcwpData.currentMonth}&year=${bcwpData.currentYear}`;
});

document.getElementById('next-month').addEventListener('click', () => {
    bcwpData.currentMonth++;
    if (bcwpData.currentMonth > 12) {
        bcwpData.currentMonth = 1;
        bcwpData.currentYear++;
    }
    window.location.href = `?month=${bcwpData.currentMonth}&year=${bcwpData.currentYear}`;
});

document.getElementById('new-event-btn').addEventListener('click', () => {
    showCreateEventModal();
});

document.getElementById('export-ical-btn').addEventListener('click', () => {
    window.location.href = `${bcwpData.restUrl}/projects/${bcwpData.projectId}/events/ical`;
});

function showCreateEventModal(date = null) {
    const modal = document.createElement('div');
    modal.className = 'bcwp-modal';
    modal.innerHTML = `
        <div class="bcwp-modal-content">
            <div class="bcwp-modal-header">
                <h2>New Event</h2>
                <button class="bcwp-modal-close">&times;</button>
            </div>
            <div class="bcwp-modal-body">
                <form id="create-event-form">
                    <div class="bcwp-form-group">
                        <label>Event Title *</label>
                        <input type="text" name="title" required>
                    </div>
                    <div class="bcwp-form-group">
                        <label>Description</label>
                        <textarea name="description" rows="3"></textarea>
                    </div>
                    <div class="bcwp-form-group">
                        <label>Start Date/Time *</label>
                        <input type="datetime-local" name="start_datetime" required value="${date ? date + 'T09:00' : ''}">
                    </div>
                    <div class="bcwp-form-group">
                        <label>End Date/Time *</label>
                        <input type="datetime-local" name="end_datetime" required value="${date ? date + 'T10:00' : ''}">
                    </div>
                    <div class="bcwp-form-group">
                        <label>Location</label>
                        <input type="text" name="location">
                    </div>
                    <div class="bcwp-form-actions">
                        <button type="submit" class="bcwp-btn bcwp-btn-primary">Create Event</button>
                        <button type="button" class="bcwp-btn bcwp-btn-secondary bcwp-modal-close">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    `;

    document.body.appendChild(modal);

    modal.querySelectorAll('.bcwp-modal-close').forEach(btn => {
        btn.addEventListener('click', () => modal.remove());
    });

    document.getElementById('create-event-form').addEventListener('submit', async (e) => {
        e.preventDefault();
        const formData = new FormData(e.target);
        const data = {
            title: formData.get('title'),
            description: formData.get('description'),
            location: formData.get('location'),
            start_datetime: formData.get('start_datetime'),
            end_datetime: formData.get('end_datetime')
        };

        try {
            const response = await fetch(`${bcwpData.restUrl}/projects/${bcwpData.projectId}/events`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-WP-Nonce': bcwpData.nonce
                },
                body: JSON.stringify(data)
            });

            if (response.ok) {
                modal.remove();
                window.location.reload();
            }
        } catch (error) {
            console.error('Failed to create event:', error);
        }
    });
}

renderCalendar();
</script>
<script src="<?php echo BCWP_PLUGIN_URL; ?>assets/js/frontend.js"></script>

</body>
</html>
