<?php
/**
 * My Schedule - Personal calendar across all projects
 */

PFOB_Template::header( 'My Schedule' );

$user_id = get_current_user_id();
$current_month = isset( $_GET['month'] ) ? intval( $_GET['month'] ) : date( 'n' );
$current_year = isset( $_GET['year'] ) ? intval( $_GET['year'] ) : date( 'Y' );

// Get all projects user is a member of
$user_projects = PFOB_Project::get_user_projects( $user_id );
$all_events = array();

// Collect events from all projects
$start_date = "$current_year-$current_month-01";
$end_date = date( 'Y-m-t', strtotime( $start_date ) );

foreach ( $user_projects as $project ) {
    $project_events = PFOB_Event::get_project_events( $project->id, $start_date, $end_date );
    foreach ( $project_events as $event ) {
        $event->project_name = $project->name;
        $event->project_slug = $project->slug;
        $all_events[] = $event;
    }
}

// Get upcoming events across all projects
$upcoming_events = array();
foreach ( $user_projects as $project ) {
    $project_upcoming = PFOB_Event::get_upcoming_events( $project->id, 5 );
    foreach ( $project_upcoming as $event ) {
        $event->project_name = $project->name;
        $event->project_slug = $project->slug;
        $upcoming_events[] = $event;
    }
}

// Sort upcoming events by date
usort( $upcoming_events, function( $a, $b ) {
    return strtotime( $a->start_datetime ) - strtotime( $b->start_datetime );
} );
$upcoming_events = array_slice( $upcoming_events, 0, 10 );
?>

<div class="pfob-container">
    <?php PFOB_Template::navigation(); ?>

    <main class="pfob-main pfob-schedule">

        <div class="pfob-page-header">
            <h1>My Schedule</h1>
            <p class="pfob-subtitle">All your events across all projects</p>
        </div>

        <div class="pfob-calendar-controls">
            <button id="prev-month">&larr;</button>
            <h2 id="current-month-year"><?php echo date( 'F Y', strtotime( "$current_year-$current_month-01" ) ); ?></h2>
            <button id="next-month">&rarr;</button>
        </div>

        <div class="pfob-calendar" id="calendar-grid">
            <!-- Calendar will be generated by JavaScript -->
        </div>

        <div class="pfob-upcoming-events">
            <h3>Upcoming Events</h3>
            <div id="upcoming-events-list">
                <?php if ( empty( $upcoming_events ) ) : ?>
                    <p class="pfob-empty-text">No upcoming events</p>
                <?php else : ?>
                    <?php foreach ( $upcoming_events as $event ) : ?>
                        <div class="pfob-event-item">
                            <div class="pfob-event-date">
                                <?php echo date( 'M j', strtotime( $event->start_datetime ) ); ?>
                            </div>
                            <div class="pfob-event-details">
                                <strong><?php echo esc_html( $event->title ); ?></strong>
                                <span class="pfob-event-project">
                                    <a href="<?php echo home_url( '/projectfob/projects/' . $event->project_slug . '/schedule/' ); ?>">
                                        <?php echo esc_html( $event->project_name ); ?>
                                    </a>
                                </span>
                                <?php if ( $event->location ) : ?>
                                    <span class="pfob-event-location">📍 <?php echo esc_html( $event->location ); ?></span>
                                <?php endif; ?>
                                <span class="pfob-event-time">
                                    <?php echo date( 'g:i a', strtotime( $event->start_datetime ) ); ?>
                                </span>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>

        <?php if ( ! empty( $user_projects ) ) : ?>
            <div class="pfob-schedule-projects">
                <h3>Add Event to Project</h3>
                <div class="pfob-project-list">
                    <?php foreach ( $user_projects as $project ) : ?>
                        <a href="<?php echo home_url( '/projectfob/projects/' . $project->slug . '/schedule/' ); ?>"
                           class="pfob-project-card">
                            <strong><?php echo esc_html( $project->name ); ?></strong>
                            <span>View project schedule →</span>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

    </main>
</div>

<style>
.pfob-calendar-controls {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin: 30px 0;
    padding: 0 20px;
}

.pfob-calendar-controls button {
    background: #2d9061;
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
}

.pfob-calendar-controls button:hover {
    background: #247a50;
}

.pfob-calendar {
    background: white;
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 30px;
}

.pfob-calendar-header {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    margin-bottom: 10px;
}

.pfob-calendar-day-name {
    text-align: center;
    font-weight: 600;
    padding: 10px;
    color: #666;
}

.pfob-calendar-days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    background: #e0e0e0;
    border: 1px solid #e0e0e0;
}

.pfob-calendar-cell {
    background: white;
    min-height: 100px;
    padding: 8px;
    cursor: pointer;
    position: relative;
}

.pfob-calendar-cell.pfob-empty {
    background: #f5f5f5;
    cursor: default;
}

.pfob-calendar-cell:hover:not(.pfob-empty) {
    background: #f9f9f9;
}

.pfob-day-number {
    font-weight: 600;
    margin-bottom: 5px;
}

.pfob-day-events {
    display: flex;
    flex-wrap: wrap;
    gap: 3px;
}

.pfob-event-dot {
    width: 6px;
    height: 6px;
    background: #2d9061;
    border-radius: 50%;
}

.pfob-upcoming-events {
    background: white;
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 30px;
}

.pfob-upcoming-events h3 {
    margin-top: 0;
    margin-bottom: 20px;
}

.pfob-event-item {
    display: flex;
    gap: 15px;
    padding: 15px;
    border-bottom: 1px solid #eee;
}

.pfob-event-item:last-child {
    border-bottom: none;
}

.pfob-event-date {
    flex-shrink: 0;
    width: 60px;
    text-align: center;
    font-weight: 600;
    color: #2d9061;
}

.pfob-event-details {
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    gap: 5px;
}

.pfob-event-project {
    font-size: 0.9em;
    color: #666;
}

.pfob-event-project a {
    color: #2d9061;
    text-decoration: none;
}

.pfob-event-project a:hover {
    text-decoration: underline;
}

.pfob-event-location,
.pfob-event-time {
    font-size: 0.85em;
    color: #888;
}

.pfob-schedule-projects {
    background: white;
    border-radius: 8px;
    padding: 20px;
}

.pfob-schedule-projects h3 {
    margin-top: 0;
    margin-bottom: 20px;
}

.pfob-project-list {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    gap: 15px;
}

.pfob-project-card {
    display: flex;
    flex-direction: column;
    gap: 8px;
    padding: 15px;
    background: #f7f6f3;
    border-radius: 6px;
    text-decoration: none;
    color: inherit;
    transition: all 0.2s;
}

.pfob-project-card:hover {
    background: #2d9061;
    color: white;
    transform: translateY(-2px);
}

.pfob-project-card span {
    font-size: 0.9em;
    opacity: 0.8;
}

.pfob-empty-text {
    color: #999;
    font-style: italic;
    text-align: center;
    padding: 40px;
}
</style>

<script>
const pfobData = {
    restUrl: '<?php echo rest_url( 'projectfob/v1' ); ?>',
    nonce: '<?php echo wp_create_nonce( 'wp_rest' ); ?>',
    currentMonth: <?php echo $current_month; ?>,
    currentYear: <?php echo $current_year; ?>,
    events: <?php echo json_encode( $all_events ); ?>
};

function renderCalendar() {
    const firstDay = new Date(pfobData.currentYear, pfobData.currentMonth - 1, 1);
    const lastDay = new Date(pfobData.currentYear, pfobData.currentMonth, 0);
    const daysInMonth = lastDay.getDate();
    const startDay = firstDay.getDay();

    let html = '<div class="pfob-calendar-header">';
    ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].forEach(day => {
        html += `<div class="pfob-calendar-day-name">${day}</div>`;
    });
    html += '</div><div class="pfob-calendar-days">';

    for (let i = 0; i < startDay; i++) {
        html += '<div class="pfob-calendar-cell pfob-empty"></div>';
    }

    for (let day = 1; day <= daysInMonth; day++) {
        const dateStr = `${pfobData.currentYear}-${String(pfobData.currentMonth).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const dayEvents = pfobData.events.filter(e => e.start_datetime.startsWith(dateStr));

        html += `<div class="pfob-calendar-cell" data-date="${dateStr}">
            <div class="pfob-day-number">${day}</div>
            <div class="pfob-day-events">`;

        dayEvents.forEach(event => {
            html += `<div class="pfob-event-dot" title="${event.title} (${event.project_name})"></div>`;
        });

        html += '</div></div>';
    }

    html += '</div>';
    document.getElementById('calendar-grid').innerHTML = html;
}

document.getElementById('prev-month').addEventListener('click', () => {
    pfobData.currentMonth--;
    if (pfobData.currentMonth < 1) {
        pfobData.currentMonth = 12;
        pfobData.currentYear--;
    }
    window.location.href = `?month=${pfobData.currentMonth}&year=${pfobData.currentYear}`;
});

document.getElementById('next-month').addEventListener('click', () => {
    pfobData.currentMonth++;
    if (pfobData.currentMonth > 12) {
        pfobData.currentMonth = 1;
        pfobData.currentYear++;
    }
    window.location.href = `?month=${pfobData.currentMonth}&year=${pfobData.currentYear}`;
});

renderCalendar();
</script>
<script src="<?php echo PFOB_PLUGIN_URL; ?>assets/js/frontend.js?ver=<?php echo PFOB_VERSION; ?>"></script>

</body>
</html>
